name: Yanzz RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Enable RDP
        shell: pwsh
        run: |
          Write-Host "Enabling RDP..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service TermService -Force

      - name: Create User
        shell: pwsh
        run: |
          Write-Host "Creating user 'Yanzz' with a random password..."
          $password = -join ((33..126) | Get-Random -Count 12 | % {[char]$_})
          $secure   = ConvertTo-SecureString $password -AsPlainText -Force
          if (Get-LocalUser -Name "Yanzz" -ErrorAction SilentlyContinue) {
            Remove-LocalUser -Name "Yanzz"
          }
          New-LocalUser -Name "Yanzz" -Password $secure -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "Yanzz"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Yanzz"
          "RDP_USER=Yanzz"  | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RDP_PASS=$password" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Cloudflared
        shell: pwsh
        run: |
          Write-Host "Installing cloudflared..."
          Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
          Move-Item cloudflared.exe $env:USERPROFILE\cloudflared.exe
          echo "$env:USERPROFILE" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Start Cloudflare Tunnel
        shell: pwsh
        run: |
          $hostname="rdp.${{ secrets.CF_ZONE }}"
          Write-Host "Starting Cloudflare Tunnel for $hostname ..."
          Start-Process -FilePath "$env:USERPROFILE\cloudflared.exe" -ArgumentList "tunnel --no-autoupdate run --token ${{ secrets.CF_API_TOKEN }} --url rdp://localhost:3389 --hostname $hostname" -NoNewWindow
          Start-Sleep -Seconds 15

      - name: Show RDP Info
        shell: pwsh
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: rdp.${{ secrets.CF_ZONE }}:3389"
          Write-Host "Username: $env:RDP_USER"
          Write-Host "Password: $env:RDP_PASS"
          Write-Host "==================`n"
          while ($true) { Start-Sleep -Seconds 300 }
