name: Windows RDP via Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Set environment variables
        run: |
          echo "RDP_USERNAME=${{ secrets.RDP_USERNAME }}" >> $GITHUB_ENV
          echo "RDP_PASSWORD=${{ secrets.RDP_PASSWORD }}" >> $GITHUB_ENV
          echo "RDP_SUBDOMAIN=${{ secrets.RDP_SUBDOMAIN }}" >> $GITHUB_ENV
          echo "CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}" >> $GITHUB_ENV

      - name: Enable RDP & Firewall
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create RDP user
        run: |
          net user $env:RDP_USERNAME $env:RDP_PASSWORD /add
          net localgroup "Administrators" $env:RDP_USERNAME /add

      - name: Install cloudflared
        run: |
          Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.msi -OutFile cloudflared.msi
          Start-Process msiexec.exe -ArgumentList '/i cloudflared.msi /quiet' -Wait

      - name: Login cloudflared using API token
        run: |
          cloudflared login --token $env:CF_API_TOKEN

      - name: Create and run tunnel
        run: |
          cloudflared tunnel create rdp-tunnel
          cloudflared tunnel route dns rdp-tunnel $env:RDP_SUBDOMAIN
          cloudflared tunnel run rdp-tunnel
          
      - name: Show access info
        run: |
          echo "RDP Host: $env:RDP_SUBDOMAIN"
          echo "Username: $env:RDP_USERNAME"
          echo "Password: $env:RDP_PASSWORD"
